#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-y += cell2
ifdef CONFIG_DEBUG_BUILD
cell2_libs=common
else
cell2_libs=libskc
endif

cell2: $(cell2_libs) libsk sk-capdl
