#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-y += cell1
ifdef CONFIG_DEBUG_BUILD
cell1_libs=common
else
cell1_libs=libskc
endif

cell1: $(cell1_libs) libsk sk-capdl
